application: cpd200-nuggets
version: tasks-001
module: tasks
runtime: python27
api_version: 1
threadsafe: true

instance_class: B2
manual_scaling:
  instances: 2

handlers:
- url: /css
  static_dir: css

- url: /tasks
  script: tasks.app